### ISSUE TITLE
User Prisma Model

### ISSUE THREAD

**Issue by jstelnik** [ChrisWilhelm/MathForABetterWorld#4]
name, email, id, password, admin/volunteer

**Comment by i-api** [comment]
Forgot to close this. User was done over 2 weeks ago, but had a bunch of updates over the past week.

commit ce7351a7fe38f08f0bb7fb6ddee48f27579b0dc3 (origin/dev, dev)
Merge: 1c6ea2e 7ed6396
Author: Christopher Wilhelm <70656080+ChrisWilhelm@users.noreply.github.com>
Date:   Thu Feb 23 13:34:42 2023 -0500

    Merge pull request #20 from ChrisWilhelm/Chris_feature_user_crud
    
    Chris feature user crud

Final schema turned out like this:
model User {
  id            Int         @id @default(autoincrement())
  email         String      @unique
  name          String
  checkedPallot FoodEntry[]
  shiftsWorked  Shift[]
}
